spring:

  mail:
    host: smtp.yandex.ru
    username: course.x@yandex.ru
    password: 
    port: 465
    protocol: smtps

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/myblog
    hikari:
      username: postgres
      password: defender

mail:
  debug: true